services:
  - type: web
    name: wattwise-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: EMPHASIZE_SSL
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: wattwise-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false # User must manually add this in Render dashboard

databases:
  - name: wattwise-db
    databaseName: wattwise_db
    user: wattwise_user
    plan: free # Render Free Tier Postgres
